.PHONY: imprimir 
#.PHONY es una opcion util para cuando una meta no tiene requisitos.
# el orden de ejecucion es <meta>: <parametros necesarios>
imprimir:
	cc primerc.c
	./a.out
clean:
	rm *~ *.dat *.png
#Para ejecutar una parte especifica del Makefile en la terminal se escribe el codigo "make <parte especifica>"
#clean es una opcion util para borrar los datos creados por make, de esta forma make puede volver a ser utilizado ya que no habra archivos creados (o actualizados)
